### ISSUE TITLE
Verify radio and checkboxes don't visually change if user has custom colours

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/verify-frontend#213]
If a user has chosen custom colours (for accessibility / visibility reasons), the Verify checkboxes and radios do not visually change when selected.

Video of the issue:
![verify-custom-colours-custom-radios](https://cloud.githubusercontent.com/assets/2204224/18093449/c537d168-6ec7-11e6-8064-dc5c68c981a0.gif)

What's wrong / expected:
The radios and checkboxes should visually change when selected.

Tested on:
Firefox with custom colours picked (in settings)
Verify production environment.

Tried after reading this blog post:
https://accessibility.blog.gov.uk/2016/05/26/accessibility-and-me-marian-foley/

**Comment by robinwhittleton** [comment]
Hopefully this will be resolved by fixing https://github.com/alphagov/govuk_elements/pull/296, cutting a new release of elements and integrating that into Verify. I’ve been using Verify as a test-bed, so that shouldn’t be too difficult.

**Comment by edwardhorsford** [comment]
I imagine that elements PR will want to be heavily tested, which may take some time...
