### ISSUE TITLE
Post Office requiring Photocard licence even when the user says they haven't got one. 

### ISSUE THREAD

**Issue by accessiblewebuk** [alphagov/verify-frontend#241]
When specifiying that you don't have a GB photocard licence (in combination with saying yes to a passport, no to other docs, and yes to being able to install a mobile app) Post Office is recommended. However their first page states: 

Before proceeding, you will need the following documents:

    your email address
    your mobile phone
    a valid passport
    a valid UK driving licence (photoID)
    your bank account number
    or your creditcard number

So presumably the application would fail (didn't try to get further than this point).

**Comment by robinwhittleton** [comment]
Hi @accessiblewebuk , we‘ve checked and this is on the Post Office website rather than coming from Verify. Could you let them know? Thanks!
