### ISSUE TITLE
Inconsistent timing promises

### ISSUE THREAD

**Issue by davidread** [alphagov/verify-frontend#256]
"Verifying your identity takes about 15 minutes to complete, but you only have to do it once. You can then access other government services in less than 1 minute wherever you see the GOV.UK Verify logo."
https://www.signin.service.gov.uk/about-identity-accounts

"It takes about 10 minutes to verify your identity the first time you use GOV.UK Verify, and a couple of minutes any time after that."
https://www.gov.uk/government/publications/introducing-govuk-verify/introducing-govuk-verify

**Comment by robinwhittleton** [comment]
Submitted that as an issue to publishing, via the feedback form.

**Comment by willp-bl** [comment]
Closing this issue as the feedback to make the change elsewhere has been sent, thanks for the report
