### ISSUE TITLE
No 'feedback' link on confirmation page

### ISSUE THREAD

**Issue by davidread** [alphagov/verify-frontend#257]
I signed up to Verify and it takes me to:

https://www.signin.service.gov.uk/confirmation

but this doesn't have anywhere to provide feedback or ask for help. I think all the previous ones did. Surely after you've gone through the long-winded process with the third-party provider there might be some questions or feedback? The end of the process seems the obvious place to solicit it, no?

**Comment by robinwhittleton** [comment]
This was purposefully removed in https://github.com/alphagov/verify-frontend/commit/6e69c524b9add2f2edd39095ec0515ac5d1a32db. I agree though that it could be useful in capturing people’s thoughts at the end of the sign up process.

**Comment by willp-bl** [comment]
We don't want users to delay when that page is shown as that is not the end of the journey, and there is a limited time for the matching process to complete.  The 'Feedback' link in the page footer should still be present on that page.

Closing this issue, but thanks for the report
