### ISSUE TITLE
Testing Approach on Verify-Frontend

### ISSUE THREAD

**Issue by thomasalanlee** [alphagov/verify-frontend#295]
## Background
Following a number of conversations on the testing approach in this project we're attempting to define a set of guidelines for testing Verify-Frontend

## Feature tests
We use feature tests to test that pages are rendered as expected based on interactions with the user. There should be a relatively small number of these for each page and they should use real application classes not stubs/mocks
 
We should aim to make feature tests as descriptive as possible. 
Feature tests are about testing user interactions with the application. As such assertions should be about the state of the application from the user's perspective, try and avoid asserting on application internals e.g. headers/cookie values in these tests - these types of things should be tested in controller tests

## Controller tests
Controller tests should used to test any logic that sits in a controller. These still use Rails request-response cycle so are not as fast as unit tests but do not render the views so are faster than Feature tests. Depending on the complexity of the logic, there should be more of these per page than feature specs.
These test can still take advantage of the existing fixtures (things under /stub) so try and use these where possible instead of mocking things out. 

## Unit tests
Unit tests should be preferred where it makes sense to extract logic from the controller. These tests are very fast to run and being relatively self-contained should give good feedback to help you fix any issues

**Comment by vixus0** [comment]
### Controllers with logic and no controller tests

_These are probably tested via feature tests._

* AuthnRequestController
* CertifiedCompanyUnavailableController
* ConfigurableJourneyController 😛 
* ConfirmYourIdentityController
* FeedbackController
* RedirectToIdpWarningController
* ResponseProcessingController
* ServiceStatusController
* StartController

**Comment by willp-bl** [comment]
Can this be written up as an ADR?

**Comment by owenblacker** [comment]
This repo is only temporarily unarchived in order to clean up some Terraform; this issue is no longer pertinent
