### ISSUE TITLE
Verify buttons include original green bottom border

### ISSUE THREAD

**Issue by nickcolley** [alphagov/verify-frontend#389]
![screen shot 2017-10-26 at 12 55 19](https://user-images.githubusercontent.com/2445413/32051556-fa20e6fe-ba4c-11e7-8306-ded67c9b3df6.png)

**Comment by jakubmiarka** [comment]
Thanks Nick, I raised this in our backlog under [TT-1489](https://govukverify.atlassian.net/browse/TT-1489) to fix the shadow.

**Comment by jakubmiarka** [comment]
Fixed by #391 and released. Closing now.
