### ISSUE TITLE
On mobile Chrome the English/Welsh language selector is at the bottom of the page

### ISSUE THREAD

**Issue by willp-bl** [alphagov/verify-frontend#418]
At least on the /start page

**Comment by jakubmiarka** [comment]
This is intentional as per [TT-941](https://govukverify.atlassian.net/browse/TT-941), to save space and reduce scrolling on mobile devices.

**Comment by willp-bl** [comment]
Ok, thanks for the quick reply.  I'll close this issue.  For what it's worth HMRC's mobile site still has it in the top right, however.
