### ISSUE TITLE
Frontend needs config service running to show static pages

### ISSUE THREAD

**Issue by willp-bl** [alphagov/verify-frontend#523]
Previously the app could show the cookies, privacy policy and feedback pages by just starting it standalone.  Now those pages are not displayed because the app can't get to a config service.

This is a regression because it means the frontend in production will break if a config service is not running - and it will not be able to accept feedback etc.

**Comment by jakubmiarka** [comment]
Introduced by [PR#488](https://github.com/alphagov/verify-frontend/pull/488)

@karlbaker02 FYI

**Comment by jakubmiarka** [comment]
This has now been fixed by changing the logic for loading RP translations.
