### ISSUE TITLE
Possible to run the verify frontend with a stubbed API_HOST in development?

### ISSUE THREAD

**Issue by matthewford** [alphagov/verify-frontend#53]
Hello,

Trying to get this running to have a look at the verify flow, seems it requires the API to be running, is there a mocked/stubbed api?

**Comment by richardTowers** [comment]
Not yet I'm afraid. It's something we'd like to add though.

**Comment by richardTowers** [comment]
I've made a start on one here:

https://github.com/richardTowers/mock-verify-hub

Which should be sufficient to see all the pages in the flow. Let me know if you have any trouble with it. :ribbon:

**Comment by matthewford** [comment]
Thanks, I'll check it out.

**Comment by richardTowers** [comment]
I raised #178 to sort this out properly. May still need some discussion though.

**Comment by robinwhittleton** [comment]
That PR was merged so this issue can be closed. Thanks for raising it @matthewford
